"""Create api_keys table

Revision ID: d8b2597e6f13
Revises: 
Create Date: 2025-10-20 16:02:43.599112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8b2597e6f13'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('discord_id', sa.BigInteger(), nullable=False, comment='Discord user ID of the key owner'),
    sa.Column('hashed_key', sa.String(length=255), nullable=False, comment='Bcrypt/Argon2 hashed API key'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='User-provided label for the key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True, comment='Last time this key was used for authentication'),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True, comment='When the key was revoked (NULL = active)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hashed_key')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_discord_id'), ['discord_id'], unique=False)
        batch_op.create_index('ix_api_keys_discord_id_active', ['discord_id', 'revoked_at'], unique=False, postgresql_where='revoked_at IS NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index('ix_api_keys_discord_id_active', postgresql_where='revoked_at IS NULL')
        batch_op.drop_index(batch_op.f('ix_api_keys_discord_id'))

    op.drop_table('api_keys')
    # ### end Alembic commands ###
