"""Create session_tokens table

Revision ID: a34bd3d948f4
Revises: d8b2597e6f13
Create Date: 2026-01-02 21:47:46.927181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a34bd3d948f4'
down_revision: Union[str, None] = 'd8b2597e6f13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
