"""Create session_tokens table

Revision ID: ce373b6fac51
Revises: d8b2597e6f13
Create Date: 2026-01-02 22:09:55.492207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce373b6fac51'
down_revision: Union[str, None] = 'd8b2597e6f13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('api_key_id', sa.UUID(), nullable=False, comment='API key that generated this session token'),
    sa.Column('hashed_token', sa.String(length=255), nullable=False, comment='Bcrypt hashed session token'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='Token expiration timestamp'),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True, comment='Last time this token was used for authentication'),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True, comment='Manual revocation timestamp (NULL = active)'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='IP address that created this token'),
    sa.Column('user_agent', sa.String(length=255), nullable=True, comment='User agent string from token creation'),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hashed_token')
    )
    with op.batch_alter_table('session_tokens', schema=None) as batch_op:
        batch_op.create_index('ix_session_tokens_api_key_active', ['api_key_id', 'revoked_at'], unique=False, postgresql_where='revoked_at IS NULL')
        batch_op.create_index(batch_op.f('ix_session_tokens_api_key_id'), ['api_key_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_tokens_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index('ix_session_tokens_expires_at_active', ['expires_at', 'revoked_at'], unique=False, postgresql_where='revoked_at IS NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_tokens', schema=None) as batch_op:
        batch_op.drop_index('ix_session_tokens_expires_at_active', postgresql_where='revoked_at IS NULL')
        batch_op.drop_index(batch_op.f('ix_session_tokens_expires_at'))
        batch_op.drop_index(batch_op.f('ix_session_tokens_api_key_id'))
        batch_op.drop_index('ix_session_tokens_api_key_active', postgresql_where='revoked_at IS NULL')

    op.drop_table('session_tokens')
    # ### end Alembic commands ###
